[package]
name = "librespot-playback"
version = "0.1.3"
authors = ["Sasha Hilton <sashahilton00@gmail.com>"]
description="The audio playback logic for librespot"
license="MIT"
edition = "2018"

[dependencies.librespot-audio]
path = "../audio"
version = "0.1.3"
[dependencies.librespot-core]
path = "../core"
version = "0.1.3"
[dependencies.librespot-metadata]
path = "../metadata"
version = "0.1.3"

[dependencies]
futures = "0.1"
log = "0.4"
byteorder = "1.3"
shell-words = "0.1.0"

alsa            = { version = "0.2", optional = true }
portaudio-rs    = { version = "0.3", optional = true }
libpulse-sys    = { version = "0.0.0", optional = true }
jack            = { version = "0.5", optional = true }
libc            = { version = "0.2", optional = true }
rodio           = { version = "0.9", optional = true, default-features = false }
cpal            = { version = "0.8", optional = true }
sdl2            = { version = "0.34.3", optional = true, git = "https://github.com/raedwulf/rust-sdl2", branch = "fix-sdl-opening-for-sndio" }
gstreamer       = { version = "0.15", optional = true }
gstreamer-app   = { version = "0.15", optional = true }
glib            = { version = "0.9", optional = true }
zerocopy        = { version = "0.2", optional = true }

[features]
alsa-backend = ["alsa"]
portaudio-backend = ["portaudio-rs"]
pulseaudio-backend = ["libpulse-sys", "libc"]
jackaudio-backend = ["jack"]
rodio-backend = ["rodio", "cpal"]
sdl-backend = ["sdl2"]
gstreamer-backend = ["gstreamer", "gstreamer-app", "glib", "zerocopy"]
